/**
 * underscore.string additions.
 */

(function(ns) {
  var EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/ig;


  /**
   * Generate random alphanumeric strings.
   *
   * Strings generated by this method are NOT cryptographically safe.
   *
   * @param num {Integer} no. of strings to generate.
   * @param len {Integer} no. of characters each string should have.
   *
   * @return {Array}
   */
  ns.gen = function(num, len) {
    var ret = [];
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (var i=0; i<num; ++i) {
      var text = "";
      for( var j=0; j < len; j++ ) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
      }
      ret.push(text);
    }

    return ret;
  };


  /**
   * Extract email addresses from given string.
   *
   * This method uses regex matcher to extract strings, allowing it to 
   * handle cases where other strings (e.g. person names) are interleaved with 
   * the addresses.
   *
   * @param {String} str The email address string.
   * 
   * @return {Array}
   */
  ns.extractEmailAddresses = function(str) {
    return str.match(EMAIL_REGEX);
  };

}(_.str));

