/**
 * underscore.string additions.
 */

(function(ns) {
  /**
   * Generate random alphanumeric strings.
   *
   * Strings generated by this method are NOT cryptographically safe.
   *
   * @param num {Integer} no. of strings to generate.
   * @param len {Integer} no. of characters each string should have.
   *
   * @return {Array}
   */
  ns.gen = function(num, len) {
    var ret = [];
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (var i=0; i<num; ++i) {
      var text = "";
      for( var j=0; j < len; j++ ) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
      }
      ret.push(text);
    }

    return ret;
  };

}(_.str));

